### ISSUE TITLE
I must be mistaken. TomNguyen.ETH has been resolved and in use for years. A different controller Wallet was used to set it. I thought this was the modification. Not sure why it’s not.

### ISSUE THREAD

**Issue by ManROC87** [ensdomains/governance#12]
I must be mistaken. TomNguyen.ETH has been resolved and in use for years. A different controller Wallet was used to set it. I thought this was the modification. Not sure why it’s not.

_Originally posted by @mrtomnguyen in https://github.com/ensdomains/governance/issues/9#issuecomment-1039500482_

**Comment by ManROC87** [comment]
Sorry  my mistake

**Comment by ManROC87** [comment]
Ok

**Comment by mrtomnguyen** [comment]
thanks for opening this. 
To confirm, I should have ENS to claim using the Wallet that TomNguyen.eth resolves to correct?
I had already claimed ENS on the Controller Wallet.

**Comment by makoto** [comment]
Please use github issue to report bugs. For general support, please raise a ticket on our support channel on discord
