### ISSUE TITLE
Need a custom contract to get the info about delegate including

### ISSUE THREAD

**Issue by makoto** [ensdomains/governance#2]
Returns
- Delegate token balance
- Avatar
- Eth address
- Profile

Optional fields
- com.discord
- com.twitter

**Comment by azboyzranch** [comment]
> Returns
> 
> * Delegate token balance
> * Avatar
> * Eth address
> * Profile
> 
> Optional fields
> 
> * com.discord
> * com.twitter

**Comment by azboyzranch** [comment]
>.

**Comment by azboyzranch** [comment]
Duplicate of #
